### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by cxhernandez** [msmexplorer/msmexplorer#1]
see: https://github.com/msmbuilder/msmbuilder/issues/697

**Comment by cxhernandez** [comment]
- [ ] feature projections
    - [ ] hexbin 2d landscape
    - [ ] kde 1d landscape
    - [ ] kde 2d landscape
    - [ ] cornerplot (esp good for PCA/tICA)
- [ ] msm plots
    - [ ] force-directed graph
    - [ ] raw versus msm counts
    - [ ] timescale plots
- [ ] tpt plots
    - [ ] force-directed graph
- [ ] information theory plots
    - [ ] dendrogram
    - [ ] chord diagrams
- [ ] structures
    - [ ] nglview color-by-metric
    - [ ] nglview interactive 2d landscape
    - [ ] vmd scripts (for hi-res structures)
    - [ ] pymol scripts (for hi-res structures)
    - [ ] pymol interface (e.g. [ipymol](https://github.com/cxhernandez/ipymol))
- [ ] movies
    - [ ] PC/tIC movies

cc @mpharrigan @msultan for more plot ideas

**Comment by msultan** [comment]
errorbars,
movie makers

**Comment by cxhernandez** [comment]
> errorbars

I imagine this might be done with a kwarg for relevant plots? Let me know if you had something in mind


> movie makers

Could you elaborate? Am I going to be making a movie making API?

```
Protein.move('x', 2)
Protein.rotate('y', 80)
Protein.camera.rotate('z', 20)
```

**Comment by cxhernandez** [comment]
cc-ing @nlatorra and @eigenstate, in case you have plot ideas or VMD/PyMOL scripts to contribute 😄

**Comment by cxhernandez** [comment]
bump @msultan

**Comment by cxhernandez** [comment]
bump @brookehus (once you've submitted your paper 😄)

**Comment by jeiros** [comment]
Have you considered UCSF Chimera for visualization? I know it has a Python API although I'm not too familiar with it.

Interesting repo btw! 👍

**Comment by cxhernandez** [comment]
>Have you considered UCSF Chimera for visualization? I know it has a Python API although I'm not too familiar with it.

I have, but I haven't used the Python API. Generally, I'd like to contain all dependencies within conda, and with `pychimera` it seems like you still need a local installation of Chimera which makes it kind of a deal-breaker 😕 

I think `nglview` is going to be the default for the msmexplorer, but we'll offer automated scripting tools for VMD, PyMOL, and Chimera, as people contribute them (and as soon as I think of a good API for this).
